add create network and cluster in aws

diff --git a/.circleci/config.yml b/.circleci/config.yml
--- a/.circleci/config.yml
+++ b/.circleci/config.yml
@@ -62,20 +62,54 @@ jobs:
       steps:
         - checkout
         - run:
-            name: Deploy network stack
+            name: deploy network stack
             command: |
-              aws cloudformation deploy \
-              --template-file .circleci/cf-templates/network.yml \
-              --tags project=udapeople \
-              --stack-name "network-stack-${ENV_NAME}" \
-              --parameter-overrides EnvironmentName="${ENV_NAME}" 
+              export SUCCESS=$(aws cloudformation deploy --template-file .circleci/cf-templates/network.yml  \
+                --tags project=udapeople  --stack-name "network-stack-${ENV_NAME}"    \
+                --parameter-overrides EnvironmentName="${ENV_NAME}")
+
+              echo "${SUCCESS}" > ~/result
+              if grep -E "Successfully created/updated|No changes to deploy" ~/result
+              then
+                echo "Successfully created/updated"
+                exit 0
+              else
+                echo "Could not create network stack."
+                exit 1
+              fi             
+
+    create-aws-eks:
+      <<: *aws_docker_image
+      steps:
+        - run:
+            name: check aws network exist
+            command: |
+
+                export SG=$(
+                  aws cloudformation list-exports --query "Exports[?Name==\`${ENV_NAME}-SecurityGroups\`].Value" --no-paginate --output text
+                )
+
+                export SUBNETS=$(
+                  aws cloudformation list-exports --query "Exports[?Name==\`${ENV_NAME}-SubnetIds\`].Value" --no-paginate --output text
+                )
+
+                aws eks --region us-east-1 create-cluster --name ${ENV_NAME}-cluster \
+                --role-arn arn:aws:iam::246528985509:role/UdaEKSClusterAccess \
+                --resources-vpc-config subnetIds=${SUBNETS},securityGroupIds=${SG}
 
 
 workflows:
-  build-test-lint:
+  deploy-application:
     jobs:
       - build-test-lint
       - deploy-infrastructure-network:
+          requires: [build-test-lint]
           filters:
             branches:
-              only: [deploy-network]
+              only: [master]
+      - create-aws-eks:
+          requires: [deploy-infrastructure-network]
+          filters:
+            branches:
+              only: [master]
+  
