fix cluster creation

diff --git a/.circleci/config.yml b/.circleci/config.yml
--- a/.circleci/config.yml
+++ b/.circleci/config.yml
@@ -63,7 +63,20 @@ jobs:
         - checkout
         - run:
             name: deploy network stack
-            command: .circleci/scripts/deploy-network.sh ${ENV_NAME}        
+            command: |
+              export SUCCESS=$(aws cloudformation deploy --template-file .circleci/cf-templates/network.yml  \
+                              --tags project=udapeople  --stack-name "network-stack-$ENV_NAME"    \
+                              --parameter-overrides EnvironmentName="$ENV_NAME")
+
+              echo "$SUCCESS" > ~/result
+              if grep -E "Successfully created/updated|No changes to deploy" ~/result
+              then
+              echo "Successfully created/updated"
+              exit 0
+              else
+              echo "Could not create network stack."
+              exit 1
+              fi          
             no_output_timeout: 30m
 
     deploy-aws-eks:
@@ -71,7 +84,34 @@ jobs:
       steps:
         - run:
             name: deploy eks cluster
-            command: .circleci/scripts/deploy-cluster.sh ${ENV_NAME}
+            command: |
+              export VALIDATE=$(aws eks describe-cluster --name $ENV_NAME-cluster --query 'cluster.name')
+              echo "$VALIDATE" > ~/validate
+              if cat ~/validate | grep "$ENV_NAME-cluster"
+              then
+                  echo "Cluster $ENV_NAME-cluster already exist."
+                  exit 0
+              else
+                  echo "Attempting to create the cluster $ENV_NAME-cluster"
+              fi
+
+              export SG=$(aws cloudformation list-exports --query "Exports[?Name==\`$ENV_NAME-SecurityGroups\`].Value" \
+                          --no-paginate --output text)
+
+              echo "Received SG: $SG"
+
+              export SUBNETS=$(aws cloudformation list-exports --query "Exports[?Name==\`$ENV_NAME-SubnetIds\`].Value" \
+                          --no-paginate --output text)
+
+              echo "Received Subnets: $SUBNETS"
+
+              aws eks create-cluster --name $ENV_NAME-cluster \
+                              --role-arn arn:aws:iam::246528985509:role/UdaEKSClusterAccess \
+                              --resources-vpc-config subnetIds=$SUBNETS,securityGroupIds=$SG \
+                              --region us-east-1 
+
+
+              aws eks wait cluster-active --name $ENV_NAME-cluster
             no_output_timeout: 30m
 
 workflows:
